# Generated by Django 3.2.13 on 2022-05-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fatalgram.app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('trip_start', models.DateField(blank=True, null=True)),
                ('trip_end', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo_taken', models.DateTimeField(blank=True, null=True)),
                ('photo_camera', models.CharField(max_length=200, null=True)),
                ('photo_lat', models.CharField(max_length=200, null=True)),
                ('photo_lon', models.CharField(max_length=200, null=True)),
                ('photo_alt', models.CharField(max_length=200, null=True)),
                ('photo_raw', models.ImageField(upload_to=fatalgram.app.models.path_raw)),
                ('photo_thumb', models.ImageField(upload_to=fatalgram.app.models.path_thumb)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trip')),
            ],
        ),
    ]
