# Generated by Django 3.2.13 on 2022-05-25 13:07

from django.db import migrations, models
import fatalgram.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('face_encoding', models.TextField()),
                ('face_thumb', models.ImageField(upload_to=fatalgram.app.models.path_face_thumb)),
                ('photos', models.ManyToManyField(to='app.Photo')),
            ],
        ),
    ]
