# Generated by Django 3.2.13 on 2022-05-26 07:15

from django.db import migrations, models
import django.db.models.deletion
import fatalgram.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='person',
            name='face_thumb',
        ),
        migrations.AlterField(
            model_name='person',
            name='photos',
            field=models.ManyToManyField(null=True, to='app.Photo'),
        ),
        migrations.CreateModel(
            name='PersonEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField()),
                ('face_thumb', models.ImageField(upload_to=fatalgram.app.models.path_face_thumb)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
