# Generated by Django 3.2.13 on 2022-05-26 07:40

from django.db import migrations, models
import fatalgram.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220526_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_high',
            field=models.ImageField(null=True, upload_to=fatalgram.app.models.path_highquality),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_medium',
            field=models.ImageField(null=True, upload_to=fatalgram.app.models.path_mediumquality),
        ),
    ]
